export const Colors = {
  primary: '#7b3f5e',
  primaryLight: '#a0566f',
  primaryDark: '#5c2e46',
  accent: '#e8a0b4',
  accentLight: '#f5d0dc',
  background: '#fdf5f7',
  backgroundDark: '#1a0f14',
  surface: '#ffffff',
  surfaceDark: '#2d1a22',
  text: '#2c1a25',
  textDark: '#f0e6ea',
  textSecondary: '#8a6070',
  textSecondaryDark: '#c4a0b0',
  bubbleUser: '#7b3f5e',
  bubbleAssistant: '#ffffff',
  bubbleUserText: '#ffffff',
  bubbleAssistantText: '#2c1a25',
  border: '#e8d0d8',
  borderDark: '#5c3048',
  danger: '#c0392b',
  success: '#27ae60',
  warning: '#f39c12',
  inputBg: '#f0e8eb',
  inputBgDark: '#3d2030',
  shadow: 'rgba(123, 63, 94, 0.15)',
};

export const DarkColors = {
  ...Colors,
  background: Colors.backgroundDark,
  surface: Colors.surfaceDark,
  text: Colors.textDark,
  textSecondary: Colors.textSecondaryDark,
  border: Colors.borderDark,
  inputBg: Colors.inputBgDark,
  bubbleAssistant: '#3d2030',
  bubbleAssistantText: '#f0e6ea',
};
